services:
  mdb:
    image: mysql:8.0
    container_name: mdb
    environment:
      - MYSQL_ROOT_PASSWORD=helloworld
      - MYSQL_DATABASE=blog_service
      - TZ=Asia/Shanghai
    ports:
      - "3306:3306"
  app-backend:
    container_name: app-backend
    image: app-backend:1.0.0
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_USERNAME=root
      - DATABASE_HOST=mdb
      - DATABASE_PASSWORD=helloworld
      - DATABASE_DBNAME=blog_service
      - SERVER_HTTPPORT=8080
      - TZ=Asia/Shanghai
    depends_on:
      - mdb
    entrypoint: 
      [
        "/usr/local/rest-api/scripts/startup/wait-for.sh",
        "mdb:3306",
        "--",
        "/usr/local/rest-api/api-server",
      ]
  app-web:
    container_name: app-web
    image: app-web:1.0.0
    build: ./web
    ports:
      - "3000:3000"
    environment:
      - TZ=Asia/Shanghai
      - BACKEND_URL=http://app-backend:8080
      - SITE_URL=http://localhost:3000
    depends_on:
      - app-backend

